# Site settings
name: Less Or More
email: ruffian.szh@163.com
author: ruffian
url:
resume_site:
github: https://github.com/
baseurl: "/weibo"
description: Actually, less is more!
meta_description: RUFFIAN;个人博客;
motto: It's our wits that make us men.
banner:

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

