# Site settings
name: 记事    #博客名称
email: ruffian.szh@163.com #邮箱地址
author: ruffian   #作者名
url:        #个人网站
resume_site:    #个人简历网站
github: https://github.com/   #github地址
baseurl: "/weibo"   #baseurl修改为项目名，如果项目是'***.github.io'，则设置为空''
description: Actually, less is more!
meta_description: RUFFIAN;个人博客;
motto: It's our wits that make us men.
banner:
template: http://less.bootcss.com
origin: ruffiant.github.io

editurl: "/weibo"

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/



#paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ruffiant    #github用户名称

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

